import { useMemo, useState } from 'react';

const TYPES = { floor: { label: 'Piso / placa', unit: 'm²' }, concrete: { label: 'Concreto', unit: 'm³' }, wall: { label: 'Muro', unit: 'm²' }, paint: { label: 'Pintura', unit: 'm²' } };
const MIXES = { standard: { label: 'Concreto estándar (referencial)', bags: 8, sand: 0.55, gravel: 0.85, water: 180 }, structural: { label: 'Concreto estructural (referencial)', bags: 9, sand: 0.50, gravel: 0.80, water: 175 }, lean: { label: 'Concreto pobre (referencial)', bags: 6, sand: 0.60, gravel: 0.90, water: 170 } };
const DEFAULT_PRICES = { cement: 0, sand: 0, gravel: 0, water: 0 };
function loadPrices() { try { return { ...DEFAULT_PRICES, ...JSON.parse(localStorage.getItem('masterobrix-material-prices') || '{}') }; } catch { return DEFAULT_PRICES; } }

export default function MaterialCalculator({ onClose, onAddToBudget, projects = [], onAddToMaterials }) {
  const [type, setType] = useState('floor'), [projectId, setProjectId] = useState(projects[0]?.id || ''), [length, setLength] = useState(''), [width, setWidth] = useState(''), [thickness, setThickness] = useState('0.10'), [height, setHeight] = useState('2.50'), [waste, setWaste] = useState('5'), [mix, setMix] = useState('standard'), [prices, setPrices] = useState(loadPrices), [pricesSaved, setPricesSaved] = useState(false);
  const result = useMemo(() => { const l=Number(length)||0,w=Number(width)||0,t=Number(thickness)||0,h=Number(height)||0; if(!l||!w)return{area:0,volume:0}; const area=l*w; const volume=type==='concrete'||type==='floor'?area*t:type==='wall'?area*h:0; return {area,volume:volume*(1+Math.max(0,Number(waste)||0)/100)}; }, [type,length,width,thickness,height,waste]);
  const concrete = useMemo(() => { if(!result.volume||!['floor','concrete'].includes(type))return null; const r=MIXES[mix]; return {bags:result.volume*r.bags,sand:result.volume*r.sand,gravel:result.volume*r.gravel,water:result.volume*r.water}; }, [result.volume,type,mix]);
  const estimatedCost = useMemo(() => !concrete?0:concrete.bags*Number(prices.cement||0)+concrete.sand*Number(prices.sand||0)+concrete.gravel*Number(prices.gravel||0)+concrete.water*Number(prices.water||0), [concrete,prices]);
  const item=TYPES[type];
  function updatePrice(k,v){setPricesSaved(false);setPrices(c=>({...c,[k]:v}));}
  function savePrices(){localStorage.setItem('masterobrix-material-prices',JSON.stringify(prices));setPricesSaved(true);}
  function addBudget(){if(!result.volume&&!result.area)return;const quantity=type==='paint'||type==='wall'?result.area:result.volume;const unitPrice=concrete&&result.volume?estimatedCost/result.volume:0;onAddToBudget?.({description:concrete?`${item.label} + materiales estimados`:`${item.label} (estimado)`,category:'Materiales',quantity:Number(quantity.toFixed(2)),unit:item.unit,unitPrice:Number(unitPrice.toFixed(2))});}
  function addMaterials(){if(!projectId||!concrete)return;onAddToMaterials?.({projectId,materials:[{name:'Cemento',unit:'sacos',needed:Number(concrete.bags.toFixed(1)),price:Number(prices.cement||0)},{name:'Arena',unit:'m³',needed:Number(concrete.sand.toFixed(2)),price:Number(prices.sand||0)},{name:'Grava',unit:'m³',needed:Number(concrete.gravel.toFixed(2)),price:Number(prices.gravel||0)},{name:'Agua',unit:'litros',needed:Number(concrete.water.toFixed(0)),price:Number(prices.water||0)}]});}
  const quantity=type==='paint'||type==='wall'?result.area:result.volume;
  return <div className="modal-backdrop"><section className="project-form material-calculator" aria-label="Calculadora de materiales"><div className="form-heading"><div><span className="eyebrow">HERRAMIENTA DE OBRA</span><h2>🧮 ¿Qué vas a construir?</h2></div><button type="button" onClick={onClose}>✕</button></div><p style={{marginBottom:18}}>Ingresa las medidas y MasterObrix estima cantidades para ayudarte a preparar la obra.</p>
    <label>Obra<select value={projectId} onChange={e=>setProjectId(e.target.value)}><option value="">Selecciona una obra</option>{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label>
    <label>Tipo de trabajo<select value={type} onChange={e=>setType(e.target.value)}>{Object.entries(TYPES).map(([k,v])=><option key={k} value={k}>{v.label}</option>)}</select></label>
    <div className="form-row"><label>Largo (m)<input type="number" min="0" step="0.01" value={length} onChange={e=>setLength(e.target.value)} placeholder="Ej. 5"/></label><label>Ancho (m)<input type="number" min="0" step="0.01" value={width} onChange={e=>setWidth(e.target.value)} placeholder="Ej. 4"/></label></div>
    {(type==='floor'||type==='concrete')&&<label>Espesor (m)<input type="number" min="0.01" step="0.01" value={thickness} onChange={e=>setThickness(e.target.value)} placeholder="Ej. 0.10"/></label>}{type==='wall'&&<label>Altura del muro (m)<input type="number" min="0.01" step="0.01" value={height} onChange={e=>setHeight(e.target.value)} placeholder="Ej. 2.50"/></label>}
    <label>Desperdicio / reserva (%)<input type="number" min="0" max="100" step="0.5" value={waste} onChange={e=>setWaste(e.target.value)}/></label>
    {(type==='floor'||type==='concrete')&&<label>Dosificación orientativa<select value={mix} onChange={e=>setMix(e.target.value)}>{Object.entries(MIXES).map(([k,v])=><option key={k} value={k}>{v.label}</option>)}</select></label>}
    <div className="budget-summary material-result"><div><span>Área calculada</span><strong>{result.area.toLocaleString(undefined,{maximumFractionDigits:2})} m²</strong></div><div><span>Cantidad con reserva</span><strong>{quantity.toLocaleString(undefined,{maximumFractionDigits:2})} {item.unit}</strong></div>{concrete&&<><div><span>🧱 Cemento</span><strong>{concrete.bags.toLocaleString(undefined,{maximumFractionDigits:1})} bultos</strong></div><div><span>🏖️ Arena</span><strong>{concrete.sand.toLocaleString(undefined,{maximumFractionDigits:2})} m³</strong></div><div><span>🪨 Grava</span><strong>{concrete.gravel.toLocaleString(undefined,{maximumFractionDigits:2})} m³</strong></div><div><span>💧 Agua</span><strong>{concrete.water.toLocaleString(undefined,{maximumFractionDigits:0})} L</strong></div></>}<small>⚠️ Estimación referencial. Las cantidades reales deben verificarse según especificaciones y por el responsable técnico.</small></div>
    {concrete&&<div className="budget-summary material-prices"><div className="form-heading"><div><span className="eyebrow">COSTOS</span><h3>💰 Mis precios de materiales</h3></div></div><div className="form-row"><label>Cemento / bulto<input type="number" min="0" value={prices.cement} onChange={e=>updatePrice('cement',e.target.value)}/></label><label>Arena / m³<input type="number" min="0" value={prices.sand} onChange={e=>updatePrice('sand',e.target.value)}/></label></div><div className="form-row"><label>Grava / m³<input type="number" min="0" value={prices.gravel} onChange={e=>updatePrice('gravel',e.target.value)}/></label><label>Agua / L<input type="number" min="0" value={prices.water} onChange={e=>updatePrice('water',e.target.value)}/></label></div><div><span>Costo estimado</span><strong>${estimatedCost.toLocaleString()}</strong></div><button type="button" className="form-submit" onClick={savePrices}>💾 Guardar mis precios</button>{pricesSaved&&<small>✅ Precios guardados.</small>}</div>}
    <div className="form-row"><button className="primary form-submit" type="button" disabled={!quantity} onClick={addBudget}>➕ Añadir al presupuesto</button>{concrete&&<button className="form-submit" type="button" disabled={!projectId} onClick={addMaterials}>🧱 Agregar materiales a la obra</button>}</div><button className="form-submit" type="button" onClick={onClose}>Listo</button></section></div>;
}
