import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';
import BudgetEditor from './components/BudgetEditor';
import BottomNav from './components/BottomNav';
import FormHeading from './components/FormHeading';
import { storage } from './services/storage';

const actions = [['🧮','Calcular materiales','Calcula cantidades rápidamente'],['💰','Nuevo presupuesto','Crea una cotización para tu cliente'],['🏗️','Nuevo proyecto','Organiza una obra'],['👥','Clientes','Gestiona tus contactos']];
const emptyProject = { name:'', client:'', address:'', startDate:'', budget:'' };
const emptyClient = { name:'', phone:'', email:'', company:'' };

function App() {
  const [projects,setProjects]=useState(storage.getProjects); const [clients,setClients]=useState(storage.getClients); const [budgets,setBudgets]=useState(storage.getBudgets);
  const [showForm,setShowForm]=useState(null); const [form,setForm]=useState(emptyProject); const [clientForm,setClientForm]=useState(emptyClient); const [view,setView]=useState('home');
  useEffect(()=>storage.saveProjects(projects),[projects]); useEffect(()=>storage.saveClients(clients),[clients]); useEffect(()=>storage.saveBudgets(budgets),[budgets]);
  function openProjectForm(){setForm(emptyProject);setShowForm('project');} function openClientForm(){setClientForm(emptyClient);setShowForm('client');}
  function saveProject(e){e.preventDefault();if(!form.name.trim())return;setProjects(c=>[{...form,id:crypto.randomUUID(),createdAt:new Date().toISOString()},...c]);setForm(emptyProject);setShowForm(null);}
  function saveClient(e){e.preventDefault();if(!clientForm.name.trim())return;setClients(c=>[{...clientForm,id:crypto.randomUUID()},...c]);setClientForm(emptyClient);setShowForm(null);}
  function saveBudget(budget){setBudgets(c=>[budget,...c]);setShowForm(null);setView('budgets');}
  function deleteProject(id){setProjects(c=>c.filter(p=>p.id!==id));} function deleteClient(id){setClients(c=>c.filter(c=>c.id!==id));}
  const budgetTotal=budgets.reduce((sum,b)=>sum+b.total,0);
  return <main className="app-shell"><header className="topbar"><div><span className="eyebrow">MASTEROBRIX AI</span><h1>Tu obra, bajo control.</h1><p>Herramientas simples para trabajar mejor.</p></div><div className="avatar">M</div></header>
    {view==='home'&&<><section className="hero-card"><div><span className="badge">🚧 MVP 0.5</span><h2>¿Qué quieres hacer hoy?</h2><p>Controla proyectos, clientes y presupuestos desde un solo lugar.</p></div><div className="hero-mark">M</div></section><section className="section"><div className="section-heading"><h2>Acciones rápidas</h2><span>4 herramientas</span></div><div className="action-grid">{actions.map(([icon,title,text])=><button className="action-card" key={title} type="button" onClick={()=>title==='Nuevo proyecto'?openProjectForm():title==='Clientes'?setView('clients'):title==='Nuevo presupuesto'?projects.length?setShowForm('budget'):openProjectForm():null}><span className="action-icon">{icon}</span><strong>{title}</strong><small>{text}</small></button>)}</div></section><ProjectSection projects={projects} openProjectForm={openProjectForm} deleteProject={deleteProject}/><section className="section stats-grid"><div className="stat-card"><span>Proyectos</span><strong>{projects.length}</strong></div><div className="stat-card"><span>Clientes</span><strong>{clients.length}</strong></div><div className="stat-card"><span>Presupuestos</span><strong>{budgets.length}</strong></div><div className="stat-card"><span>Total presupuestado</span><strong>${budgetTotal.toLocaleString()}</strong></div></section></>}
    {view==='projects'&&<ProjectSection projects={projects} openProjectForm={openProjectForm} deleteProject={deleteProject}/>} {view==='clients'&&<ClientSection clients={clients} openClientForm={openClientForm} deleteClient={deleteClient}/>} {view==='budgets'&&<BudgetSection budgets={budgets} projects={projects}/>} 
    {showForm==='project'&&<div className="modal-backdrop"><form className="project-form" onSubmit={saveProject}><FormHeading eyebrow="NUEVA OBRA" title="Crear proyecto" close={()=>setShowForm(null)}/><label>Nombre de la obra<input autoFocus required value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Ej. Remodelación Casa García"/></label><label>Cliente<input value={form.client} onChange={e=>setForm({...form,client:e.target.value})} placeholder="Nombre del cliente"/></label><label>Dirección<input value={form.address} onChange={e=>setForm({...form,address:e.target.value})} placeholder="Ciudad o dirección"/></label><div className="form-row"><label>Inicio<input type="date" value={form.startDate} onChange={e=>setForm({...form,startDate:e.target.value})}/></label><label>Presupuesto<input type="number" min="0" value={form.budget} onChange={e=>setForm({...form,budget:e.target.value})} placeholder="0"/></label></div><button className="primary form-submit">Guardar proyecto</button></form></div>}
    {showForm==='client'&&<div className="modal-backdrop"><form className="project-form" onSubmit={saveClient}><FormHeading eyebrow="NUEVO CLIENTE" title="Crear cliente" close={()=>setShowForm(null)}/><label>Nombre<input autoFocus required value={clientForm.name} onChange={e=>setClientForm({...clientForm,name:e.target.value})} placeholder="Nombre completo"/></label><label>Empresa<input value={clientForm.company} onChange={e=>setClientForm({...clientForm,company:e.target.value})} placeholder="Empresa (opcional)"/></label><div className="form-row"><label>Teléfono<input value={clientForm.phone} onChange={e=>setClientForm({...clientForm,phone:e.target.value})} placeholder="+1..."/></label><label>Email<input type="email" value={clientForm.email} onChange={e=>setClientForm({...clientForm,email:e.target.value})} placeholder="cliente@email.com"/></label></div><button className="primary form-submit">Guardar cliente</button></form></div>}
    {showForm==='budget'&&<BudgetEditor projects={projects} onSave={saveBudget} onClose={()=>setShowForm(null)}/>}<BottomNav view={view} setView={setView}/></main>;
}
function ProjectSection({projects,openProjectForm,deleteProject}){return <section className="section projects"><div className="section-heading"><h2>Mis proyectos</h2><button onClick={openProjectForm}>+ Nuevo</button></div>{projects.length===0?<div className="empty-state"><span>🏗️</span><strong>Aún no tienes proyectos</strong><p>Crea tu primera obra y empezamos.</p><button className="primary" onClick={openProjectForm}>+ Nuevo proyecto</button></div>:<div className="project-list">{projects.map(p=><article className="project-card" key={p.id}><div><span className="project-status">ACTIVO</span><h3>{p.name}</h3><p>{p.client||'Sin cliente'} · {p.address||'Sin dirección'}</p></div><div className="project-actions"><strong>{p.budget?`$${Number(p.budget).toLocaleString()}`:'Sin presupuesto'}</strong><button onClick={()=>deleteProject(p.id)}>Eliminar</button></div></article>)}</div>}</section>}
function ClientSection({clients,openClientForm,deleteClient}){return <section className="section"><div className="section-heading"><h2>Mis clientes</h2><button onClick={openClientForm}>+ Nuevo</button></div>{clients.length===0?<div className="empty-state"><span>👥</span><strong>Aún no tienes clientes</strong><p>Guarda tus clientes para reutilizarlos en tus obras.</p><button className="primary" onClick={openClientForm}>+ Nuevo cliente</button></div>:<div className="project-list">{clients.map(c=><article className="project-card" key={c.id}><div><span className="project-status">CLIENTE</span><h3>{c.name}</h3><p>{c.company||'Particular'} · {c.phone||c.email||'Sin contacto'}</p></div><div className="project-actions"><button onClick={()=>deleteClient(c.id)}>Eliminar</button></div></article>)}</div>}</section>}
function BudgetSection({budgets,projects}){return <section className="section"><div className="section-heading"><h2>Mis presupuestos</h2><span>{budgets.length} guardados</span></div>{budgets.length===0?<div className="empty-state"><span>💰</span><strong>Aún no tienes presupuestos</strong><p>Crea uno desde el botón de presupuesto.</p></div>:<div className="project-list">{budgets.map(b=><article className="project-card" key={b.id}><div><span className="project-status">PRESUPUESTO</span><h3>{projects.find(p=>p.id===b.projectId)?.name||'Proyecto eliminado'}</h3><p>{b.items.length} partidas · utilidad {b.margin}%</p></div><div className="project-actions"><strong>${b.total.toLocaleString()}</strong></div></article>)}</div>}</section>}
createRoot(document.getElementById('root')).render(<App/>);
